### ISSUE TITLE
Demo don't work properly

### ISSUE THREAD

**Issue by mickyloranger** [diffsky/hoffman#2]
Hi,

i have the the code below and after debuging the problem is the last line. The Error message is: TypeError: cb is not a function at .../node_modules/hoffman/node_modules/duster/index.js:46:9
Any idea?

var express = require('express');
var hoffman = require('hoffman');
var app = express();
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'dust');
app.engine('dust', hoffman.__express());
app.set('view cache', true);
hoffman.prime(app.settings.views);
...

**Comment by diffsky** [comment]
The `prime` operation is async, so it should be provided a callback. That's not at all clear from the README, so that's my fault. I have updated it.

**Comment by mickyloranger** [comment]
thanks that works properly!
